[package]
name = "comptime_tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4.13", features = ["default", "audio"] }
rand = "0.8.5"
tetris_macro = { path = "./tetris_macro" }

[workspace]
members = ["tetris_macro"]
